package com.example.dog;

public class Names2 {
    String[] nameArray2 = new String[]
            {
                    "American Staffordshire Terrier",
                    "American Staffordshire Terrier",
                    "American Staffordshire Terrier",
                    "American Staffordshire Terrier",
                    "American Staffordshire Terrier",
                    "American Staffordshire Terrier",
                    "American Staffordshire Terrier",
                    "American Staffordshire Terrier",
                    "American Staffordshire Terrier",
                    "American Staffordshire Terrier",
                    "Basset",
                    "Basset",
                    "Basset",
                    "Basset",
                    "Basset",
                    "Basset",
                    "Basset",
                    "Basset",
                    "Basset",
                    "Basset",
                    "Beagle",
                    "Beagle",
                    "Beagle",
                    "Beagle",
                    "Beagle",
                    "Beagle",
                    "Beagle",
                    "Beagle",
                    "Beagle",
                    "Beagle",
                    "Boxer",
                    "Boxer",
                    "Boxer",
                    "Boxer",
                    "Boxer",
                    "Boxer",
                    "Boxer",
                    "Boxer",
                    "Boxer",
                    "Boxer",
                    "Bull Mastiff",
                    "Bull Mastiff",
                    "Bull Mastiff",
                    "Bull Mastiff",
                    "Bull Mastiff",
                    "Bull Mastiff",
                    "Bull Mastiff",
                    "Bull Mastiff",
                    "Bull Mastiff",
                    "Bull Mastiff",
                    "Doberman",
                    "Doberman",
                    "Doberman",
                    "Doberman",
                    "Doberman",
                    "Doberman",
                    "Doberman",
                    "Doberman",
                    "Doberman",
                    "Doberman",
                    "German Shepherd",
                    "German Shepherd",
                    "German Shepherd",
                    "German Shepherd",
                    "German Shepherd",
                    "German Shepherd",
                    "German Shepherd",
                    "German Shepherd",
                    "German Shepherd",
                    "German Shepherd",
                    "Pomeranian",
                    "Pomeranian",
                    "Pomeranian",
                    "Pomeranian",
                    "Pomeranian",
                    "Pomeranian",
                    "Pomeranian",
                    "Pomeranian",
                    "Pomeranian",
                    "Pomeranian",
                    "Pug",
                    "Pug",
                    "Pug",
                    "Pug",
                    "Pug",
                    "Pug",
                    "Pug",
                    "Pug",
                    "Pug",
                    "Pug",
                    "Rhodesian Ridgeback",
                    "Rhodesian Ridgeback",
                    "Rhodesian Ridgeback",
                    "Rhodesian Ridgeback",
                    "Rhodesian Ridgeback",
                    "Rhodesian Ridgeback",
                    "Rhodesian Ridgeback",
                    "Rhodesian Ridgeback",
                    "Rhodesian Ridgeback",
                    "Rhodesian Ridgeback",
                    "Rottweiler",
                    "Rottweiler",
                    "Rottweiler",
                    "Rottweiler",
                    "Rottweiler",
                    "Rottweiler",
                    "Rottweiler",
                    "Rottweiler",
                    "Rottweiler",
                    "Rottweiler",
                    "Scotch Terrier",
                    "Scotch Terrier",
                    "Scotch Terrier",
                    "Scotch Terrier",
                    "Scotch Terrier",
                    "Scotch Terrier",
                    "Scotch Terrier",
                    "Scotch Terrier",
                    "Scotch Terrier",
                    "Scotch Terrier"
            };
}
